import React from "react";
import Image from "next/image";

const Spinner = () => {
  return (
    <>
      <Image
        src="/animation1.svg"
        width={"110px"}
        height={"113px"}
        alt=""
        objectFit="contain"
        layout="fixed"
      />
      <Image
        src="/animation2.svg"
        width={"110px"}
        height={"113px"}
        alt=""
        objectFit="contain"
        layout="fixed"
      />
      <Image
        src="/animation3.svg"
        width={"110px"}
        height={"113px"}
        alt=""
        objectFit="contain"
        layout="fixed"
      />
      <Image
        src="/animation1.svg"
        width={"110px"}
        height={"113px"}
        alt=""
        objectFit="contain"
        layout="fixed"
      />
      <Image
        src="/animation2.svg"
        width={"110px"}
        height={"113px"}
        alt=""
        objectFit="contain"
        layout="fixed"
      />
      <Image
        src="/animation3.svg"
        width={"110px"}
        height={"113px"}
        alt=""
        objectFit="contain"
        layout="fixed"
      />
      <Image
        src="/animation1.svg"
        width={"110px"}
        height={"113px"}
        alt=""
        objectFit="contain"
        layout="fixed"
      />
      <Image
        src="/animation2.svg"
        width={"110px"}
        height={"113px"}
        alt=""
        objectFit="contain"
        layout="fixed"
      />
      <Image
        src="/animation3.svg"
        width={"110px"}
        height={"113px"}
        alt=""
        objectFit="contain"
        layout="fixed"
      />
      <Image
        src="/animation1.svg"
        width={"110px"}
        height={"113px"}
        alt=""
        objectFit="contain"
        layout="fixed"
      />
      <Image
        src="/animation2.svg"
        width={"110px"}
        height={"113px"}
        alt=""
        objectFit="contain"
        layout="fixed"
      />
      <Image
        src="/animation3.svg"
        width={"110px"}
        height={"113px"}
        alt=""
        objectFit="contain"
        layout="fixed"
      />
      <Image
        src="/animation1.svg"
        width={"110px"}
        height={"113px"}
        alt=""
        objectFit="contain"
        layout="fixed"
      />
      <Image
        src="/animation2.svg"
        width={"110px"}
        height={"113px"}
        alt=""
        objectFit="contain"
        layout="fixed"
      />
      <Image
        src="/animation3.svg"
        width={"110px"}
        height={"113px"}
        alt=""
        objectFit="contain"
        layout="fixed"
      />
      <Image
        src="/animation1.svg"
        width={"110px"}
        height={"113px"}
        alt=""
        objectFit="contain"
        layout="fixed"
      />
      <Image
        src="/animation2.svg"
        width={"110px"}
        height={"113px"}
        alt=""
        objectFit="contain"
        layout="fixed"
      />
      <Image
        src="/animation3.svg"
        width={"110px"}
        height={"113px"}
        alt=""
        objectFit="contain"
        layout="fixed"
      />
      <Image
        src="/animation1.svg"
        width={"110px"}
        height={"113px"}
        alt=""
        objectFit="contain"
        layout="fixed"
      />
      <Image
        src="/animation2.svg"
        width={"110px"}
        height={"113px"}
        alt=""
        objectFit="contain"
        layout="fixed"
      />
      <Image
        src="/animation3.svg"
        width={"110px"}
        height={"113px"}
        alt=""
        objectFit="contain"
        layout="fixed"
      />
      <Image
        src="/animation1.svg"
        width={"110px"}
        height={"113px"}
        alt=""
        objectFit="contain"
        layout="fixed"
      />
      <Image
        src="/animation2.svg"
        width={"110px"}
        height={"113px"}
        alt=""
        objectFit="contain"
        layout="fixed"
      />
      <Image
        src="/animation3.svg"
        width={"110px"}
        height={"113px"}
        alt=""
        objectFit="contain"
        layout="fixed"
      />
      <Image
        src="/animation1.svg"
        width={"110px"}
        height={"113px"}
        alt=""
        objectFit="contain"
        layout="fixed"
      />
      <Image
        src="/animation2.svg"
        width={"110px"}
        height={"113px"}
        alt=""
        objectFit="contain"
        layout="fixed"
      />
      <Image
        src="/animation3.svg"
        width={"110px"}
        height={"113px"}
        alt=""
        objectFit="contain"
        layout="fixed"
      />
      <Image
        src="/animation1.svg"
        width={"110px"}
        height={"113px"}
        alt=""
        objectFit="contain"
        layout="fixed"
      />
      <Image
        src="/animation2.svg"
        width={"110px"}
        height={"113px"}
        alt=""
        objectFit="contain"
        layout="fixed"
      />
      <Image
        src="/animation3.svg"
        width={"110px"}
        height={"113px"}
        alt=""
        objectFit="contain"
        layout="fixed"
      />
      <Image
        src="/animation1.svg"
        width={"110px"}
        height={"113px"}
        alt=""
        objectFit="contain"
        layout="fixed"
      />
      <Image
        src="/animation2.svg"
        width={"110px"}
        height={"113px"}
        alt=""
        objectFit="contain"
        layout="fixed"
      />
      <Image
        src="/animation3.svg"
        width={"110px"}
        height={"113px"}
        alt=""
        objectFit="contain"
        layout="fixed"
      />
      <Image
        src="/animation1.svg"
        width={"110px"}
        height={"113px"}
        alt=""
        objectFit="contain"
        layout="fixed"
      />
      <Image
        src="/animation2.svg"
        width={"110px"}
        height={"113px"}
        alt=""
        objectFit="contain"
        layout="fixed"
      />
      <Image
        src="/animation3.svg"
        width={"110px"}
        height={"113px"}
        alt=""
        objectFit="contain"
        layout="fixed"
      />
      <Image
        src="/animation1.svg"
        width={"110px"}
        height={"113px"}
        alt=""
        objectFit="contain"
        layout="fixed"
      />
      <Image
        src="/animation2.svg"
        width={"110px"}
        height={"113px"}
        alt=""
        objectFit="contain"
        layout="fixed"
      />
      <Image
        src="/animation3.svg"
        width={"110px"}
        height={"113px"}
        alt=""
        objectFit="contain"
        layout="fixed"
      />
      <Image
        src="/animation1.svg"
        width={"110px"}
        height={"113px"}
        alt=""
        objectFit="contain"
        layout="fixed"
      />
      <Image
        src="/animation2.svg"
        width={"110px"}
        height={"113px"}
        alt=""
        objectFit="contain"
        layout="fixed"
      />
      <Image
        src="/animation3.svg"
        width={"110px"}
        height={"113px"}
        alt=""
        objectFit="contain"
        layout="fixed"
      />
    </>
  );
};

export default Spinner;
